export const randomBlogs = [
    {
      title: "Exploring the Power of Artificial Intelligence in Modern Applications",
      description: "AI is transforming industries and creating new opportunities for businesses and developers alike. Learn how AI is impacting applications and what the future holds.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-24T09:30:00Z",
      public_reactions_count: 250,
      comments_count: 50,
      reading_time_minutes: 5,
      url: "#",
    },
    {
      title: "Understanding the Basics of Git and GitHub for Version Control",
      description: "Git and GitHub are essential tools for developers. In this blog, we cover the basics of version control with Git, GitHub features, and how to integrate them into your projects.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-23T10:00:00Z",
      public_reactions_count: 180,
      comments_count: 30,
      reading_time_minutes: 7,
      url: "#",
    },
    {
      title: "JavaScript vs Python: Which Language is Right for Your Project?",
      description: "The battle between JavaScript and Python continues. This blog explores the key differences between these two popular languages and helps you decide which one suits your project best.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-22T08:00:00Z",
      public_reactions_count: 300,
      comments_count: 100,
      reading_time_minutes: 6,
      url: "#",
    },
    {
      title: "The Role of Blockchain in Enhancing Data Security",
      description: "Blockchain technology is revolutionizing the way we approach security in IT systems. Discover how blockchain can help improve data security and prevent breaches.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-21T11:30:00Z",
      public_reactions_count: 210,
      comments_count: 40,
      reading_time_minutes: 8,
      url: "#",
    },
    {
      title: "Machine Learning Algorithms Every Developer Should Know",
      description: "Machine learning algorithms are at the core of AI. This blog will help you understand the most common algorithms and how to use them in your development projects.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-20T12:00:00Z",
      public_reactions_count: 150,
      comments_count: 25,
      reading_time_minutes: 5,
      url: "#",
    },
    {
      title: "The Future of Cloud Computing and Its Impact on Development",
      description: "Cloud computing is shaping the future of development. Explore the benefits, challenges, and emerging trends in cloud computing that will affect developers and businesses.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-19T09:00:00Z",
      public_reactions_count: 120,
      comments_count: 20,
      reading_time_minutes: 6,
      url: "#",
    },
    // You can continue to add more blogs (up to 50) like this
    {
      title: "Best Practices for Writing Clean and Efficient Code",
      description: "Writing clean and efficient code is crucial for successful software development. In this blog, we discuss best practices for coding that you should follow.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-18T14:00:00Z",
      public_reactions_count: 200,
      comments_count: 45,
      reading_time_minutes: 7,
      url: "#",
    },
    {
      title: "Deep Dive Into Data Structures for Software Developers",
      description: "Data structures form the foundation of computer science. This blog takes you through various data structures and how to implement them in your projects.",
      cover_image: "https://via.placeholder.com/300",
      published_at: "2025-01-17T10:30:00Z",
      public_reactions_count: 175,
      comments_count: 35,
      reading_time_minutes: 8,
      url: "#",
    },
    // Add more blogs as needed
  ];
  